2015.12.12 23:28:00.475: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:00.835: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:01.175: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:01.641: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:02.276: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:02.640: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:02.996: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:03.357: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:03.700: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:04.056: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:04.389: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:04.731: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:05.100: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:05.440: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
2015.12.12 23:28:05.784: [/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:47] catchException Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/data/grissom/xface/node_modules/images/index.js:4:15)
    at Module._compile (module.js:399:26)
